FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install --no-frozen-lockfile

COPY . .

RUN pnpm prisma generate

CMD ["sh", "-c", "pnpm test && pnpm test:integration && pnpm test:e2e"]
